### ISSUE TITLE
Accounts can't be re-ordered

### ISSUE THREAD

**Issue by justbudget** [justbudget/justbudget#1]

**Comment by justbudget** [comment]
There is now a "reorder accounts" button. It is live on the web and will be included in the next version of the mobile apps.
![giphy-1](https://user-images.githubusercontent.com/106850056/184673221-b7d00941-9f13-4901-a876-fd729aea7cb9.gif)

**Comment by bpaulien** [comment]
So, I just realized something, which makes sense now.  I used to wonder why my mobile app didn't show the accounts in the exact same way as I saw them in the web browser.  Now I think I understand, and I wonder if there's anything else that can be done about it.
I tend to read my accounts across the top, and then down the bottom row.  kind of like reading.  So for the most part, I've got my checking, and other most frequently used accounts across the top level of accounts, and the less frequently used ones down below.

but now, when I hit the reorder accounts button, every other one are the ones across the top, and the alternating ones remaining are across the bottom.  If I want to move one, but keep them reading across, I have to figure out which position to move it into, in order to make sure it's on the top (or on the bottom, if that's what I want)

I wonder if you could include a tick box to indicate reading preference, either left to right, or top-to-bottom, then across.  If I want to move the top right account to the bottom left spot, instead of just moving it one place, I have to basically move it from 9th place to 2nd place, and everything else gets rearranged in the muddle.

**Comment by justbudget** [comment]
This is a really good point. I think having "layout preferences" might be a good idea. Some people may prefer 1 long row, or 2 rows, or maybe even 3. Some people may want to read them left to right, or top to bottom.

That being said, I actually think the way you describe it is a more sensible default, since it matches how one reads text in english. For now, I'll update the web app to display accounts from left to right. Hopefully it won't be too disruptive since now there's a way to re-order accounts. Let me know what you think!

**Comment by bpaulien** [comment]
That makes sense, and I just went in and adjusted them to the layout I like, which was much easier, reading right to left.
