### ISSUE TITLE
Consider showing account balances in the side panel

### ISSUE THREAD

**Issue by justbudget** [justbudget/justbudget#61]
From reddit thread:

https://www.reddit.com/r/justbudget/comments/vbv7dg/comment/ickqs5s/?utm_source=share&utm_medium=web2x&context=3

**Comment by justbudget** [comment]
From the further feedback, it seems like people want the accounts moved back to the sidebar entirely (and out of the "Accounts" view) https://www.reddit.com/r/justbudget/comments/wuri5d/comment/ilj2qqn/?utm_source=share&utm_medium=web2x&context=3

**Comment by blounsbury** [comment]
I wasn't entirely for or against this, I did understand the intent to separate the budget from accounts, but do like having the account balances in the sidebar, so thanks! One consideration. I think it would be nice to have hidden '+' and 'reorder' buttons. When you hover your mouse over, for example, 'Spending Accounts' the buttons show up. This would be the same as the Category buttons that show up when you hover your mouse over a Category.

**Comment by justbudget** [comment]
Thanks for the feedback! Is the goal of this to make it so that there's less clutter on the screen (since most of the time, you don't need it?)

**Comment by blounsbury** [comment]
Yes, exactly. And forgot to mention rather than having the '+Add Account' pop-up when you click on an account. Less clutter.

**Comment by justbudget** [comment]
I like this suggestion a lot! Done. Definitely an improvement visually. Thanks for the idea!

**Comment by blounsbury** [comment]
Geez, fast! My thought was actually to put a '+' add account button next to the reorder button in the Spending Accounts header (removing the '+ Add Account'). Then those buttons become visible only when you hover over the Spending Accounts header.

**Comment by justbudget** [comment]
Ohh even better! That's even cleaner. Thanks for the suggestion.

**Comment by blounsbury** [comment]
Nice! Yes, much cleaner. Even better if the icons only showed when hovering over the Spending Accounts header not individual accounts, but I'm completely satisfied as-is. Thank you!

**Comment by justbudget** [comment]
> Even better if the icons only showed when hovering over the Spending Accounts header not individual accounts,

I'm hesitant to take it that far in case the feature becomes _too_ hidden.

Thanks for all the great suggestions!

**Comment by Rick-Thomas** [comment]
Good improvement!!!   

Can I add another "nice to have"???   On the Budget screen there is the red circle with the + to add Group or Category, but is basically used for adding another Group, since Category has it's own + within the Group...    That red circle, on small screens, partially covers part of the Available number...   It's OK except when on the last Group and last Category, where I cannot scroll to see the missing part of the Available!!!

Not sure how to solve it, but I thought the solution of hovering over the Spending Account for the + Add or Order to appear was good...  Something similar with Create Group, but not sure where I'd be hovering over to have it pop up!!!

**Comment by justbudget** [comment]
Thanks for the suggestion! I've been thinking something similar for a while. I moved the + button to be in the header, and now it's smaller. Hopefully it's less intrusive now!
