### ISSUE TITLE
Transfer between regular and off budget (investment) accounts

### ISSUE THREAD

**Issue by bpaulien** [justbudget/justbudget#91]
Now that off budget accounts have been introduced, it would be nice to be able to transfer money from an on budget account to an off budget account.

One Use Case would be: I have an Investment category, and once it gets funded to a certain point, I transfer that money to an IRA.  So, it would be nice to be able to transfer from my savings to the IRA, using the investment category for the money to leave the budget through.

Another use case is paying mortgage.  Where I have the mortgage account off budget, and instead of just having a transaction that shows the money leaving from the mortgage category, it would actually transfer to the mortgage account.

Student loan payments is another case where this would be handy.

**Comment by justbudget** [comment]
I can totally see the use case for this. I believe there are a few pre-cursors that need to be added before this would work.

1) Investment accounts need to be able to have transactions, not just "balance updates". In order to show transfers, it would need to be able to show transactions in general. 
2) Transfers need to be added in-line. Right now transfers can only be done by clicking and dragging between accounts. Since on-budget and off-budget accounts are on different screens, there needs to be another way to accomplish this. So this issue is dependent on https://github.com/justbudget/justbudget/issues/96

**Comment by bpaulien** [comment]
One thing you could possibly do instead of (or in addition to?) in-line transfers would be you could drag the checking account like you currently do, except instead of going to another displayed on budget account, you pull it over to the "Investments" tab, which would then either 

- open up the investments page, so you see all the off budget accounts along the top 
- open up some kind of scrollable drop down list of off budget accounts, that you could drag to
- possibly display some kind of line break, and show another grid of all off budget accounts below all the on budget accounts, and be able to drag to one of the off budget accounts.

Just a couple little ideas that might be an option, not really sure how (or if) you'd implement it, but it was an idea.

**Comment by justbudget** [comment]
Ohhh interesting! I really like these ideas.

My favorite option is this one:

> possibly display some kind of line break, and show another grid of all off budget accounts below all the on budget accounts, and be able to drag to one of the off budget accounts.

But instead of initiating it when you drag onto "Investments", the off-budget accounts show up as soon as you start dragging, since you don't actually need to see the transactions list while dragging. Then the investments view could do the same thing but with the spending accounts.

Thanks for the suggestions!

**Comment by justbudget** [comment]
This is now possible, it was included as part of: https://github.com/justbudget/justbudget/issues/96
